version: 2.1

jobs:
  test-fork:
    docker:
      - image: cimg/ruby:3.3.5
    parallelism: 2
    steps:
      - run: echo "i'm the HEAD branch"

workflows:
  my-workflow:
    jobs:
      - test-fork
